plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT' // Оновлено для сумісності з новим Gradle
    id 'maven-publish'
}

version = "1.1-FT-1.21.4"
group = "me.maxim.invisauc"

base {
    archivesName = "invis-potion-auto-auc"
}

repositories {
    mavenCentral()
    maven { url 'https://maven.wispforest.io/releases/' } // Для owo-lib
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.4"
    mappings "net.fabricmc:yarn:1.21.4+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:0.16.7"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.110.0+1.21.4"

    // owo-lib для крутого GUI
    modImplementation "io.wispforest:owo-lib:0.12.15+1.21"
    include "io.wispforest:owo-lib:0.12.15+1.21"
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesName}" }
    }
}