# Gradle Memory
org.gradle.jvmargs=-Xmx2G

# Fabric Properties (Targeting 1.21.11 / 1.21.1 compatibility)
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.4

# Mod Properties
mod_version=1.1-FT
maven_group=me.maxim
archives_base_name=invis-potion-auto-auc

# Dependencies
fabric_version=0.116.9+1.21.1